# Generated by Django 3.0.3 on 2020-03-01 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprenour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_min', models.IntegerField()),
                ('amount_max', models.IntegerField()),
                ('background_info', models.TextField()),
                ('experiencing_area', models.TextField()),
                ('industries', models.ManyToManyField(to='enterprenour.Industry')),
                ('location', models.ManyToManyField(to='enterprenour.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InvestorDetail',
                'verbose_name_plural': 'InvestorDetails',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprenour.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.InvestorDetail')),
            ],
            options={
                'verbose_name': 'ProjectAssignment',
                'verbose_name_plural': 'ProjectAssignments',
            },
        ),
    ]
